"""init_db

Revision ID: 32ed05414427
Revises: 
Create Date: 2024-04-28 23:20:04.527319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ed05414427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('input_type', sa.String(length=255), nullable=False),
    sa.Column('output_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('model_tags',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag'], ),
    sa.PrimaryKeyConstraint('model_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_tags')
    op.drop_table('tags')
    op.drop_table('models')
    # ### end Alembic commands ###
